version: '3.9'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: paw3-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "PAW3@Password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - paw3-network

networks:
  paw3-network:
    driver: bridge

volumes:
  sqlserver-data:

